export const blogPostContent = [
  {
    title: "Placeholder post one",
    slug: "placeholder-1",
    summary: "A short placeholder summary. The real post will replace this.",
    publishedAt: "2026-07-01",
    dateLabel: "July 2026",
    readTime: "1 min read",
    tags: ["Placeholder"],
    featured: true,
  },
  {
    title: "Placeholder post two",
    slug: "placeholder-2",
    summary: "A short placeholder summary. The real post will replace this.",
    publishedAt: "2026-06-01",
    dateLabel: "June 2026",
    readTime: "1 min read",
    tags: ["Placeholder"],
    featured: true,
  },
  {
    title: "Placeholder post three",
    slug: "placeholder-3",
    summary: "A short placeholder summary. The real post will replace this.",
    publishedAt: "2026-05-01",
    dateLabel: "May 2026",
    readTime: "1 min read",
    tags: ["Placeholder"],
    featured: true,
  },
  {
    title: "Placeholder post four",
    slug: "placeholder-4",
    summary: "A short placeholder summary. The real post will replace this.",
    publishedAt: "2026-04-01",
    dateLabel: "April 2026",
    readTime: "1 min read",
    tags: ["Placeholder"],
    featured: false,
  },
];
